/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package guru.apis.apisGuru.models

import guru.apis.apisGuru.models.ApiVersion

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Meta information about API
 *
 * @param added Timestamp when the API was first added to the directory
 * @param preferred Recommended version
 * @param versions List of supported versions of the API
 */


data class API (

    /* Timestamp when the API was first added to the directory */
    @get:JsonProperty("added")
    val added: kotlinx.datetime.Instant,

    /* Recommended version */
    @get:JsonProperty("preferred")
    val preferred: kotlin.String,

    /* List of supported versions of the API */
    @get:JsonProperty("versions")
    val versions: kotlin.collections.Map<kotlin.String, ApiVersion>

) {


}

