/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package guru.apis.apisGuru.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param added Timestamp when the version was added
 * @param updated Timestamp when the version was updated
 * @param swaggerUrl URL to OpenAPI definition in JSON format
 * @param swaggerYamlUrl URL to OpenAPI definition in YAML format
 * @param info Copy of `info` section from OpenAPI definition
 * @param openapiVer The value of the `openapi` or `swagger` property of the source definition
 * @param link Link to the individual API entry for this API
 * @param externalDocs Copy of `externalDocs` section from OpenAPI definition
 */


data class ApiVersion (

    /* Timestamp when the version was added */
    @get:JsonProperty("added")
    val added: kotlinx.datetime.Instant,

    /* Timestamp when the version was updated */
    @get:JsonProperty("updated")
    val updated: kotlinx.datetime.Instant,

    /* URL to OpenAPI definition in JSON format */
    @get:JsonProperty("swaggerUrl")
    val swaggerUrl: kotlin.String,

    /* URL to OpenAPI definition in YAML format */
    @get:JsonProperty("swaggerYamlUrl")
    val swaggerYamlUrl: kotlin.String,

    /* Copy of `info` section from OpenAPI definition */
    @get:JsonProperty("info")
    val info: kotlin.Any,

    /* The value of the `openapi` or `swagger` property of the source definition */
    @get:JsonProperty("openapiVer")
    val openapiVer: kotlin.String,

    /* Link to the individual API entry for this API */
    @get:JsonProperty("link")
    val link: kotlin.String? = null,

    /* Copy of `externalDocs` section from OpenAPI definition */
    @get:JsonProperty("externalDocs")
    val externalDocs: kotlin.Any? = null

) {


}

