/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package guru.apis.apisGuru.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param `data` 
 */


data class GetServices200Response (

    @get:JsonProperty("data")
    val `data`: kotlin.collections.List<kotlin.String>? = null

) {


}

